{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "notes.fullname" . }}-backup
  labels:
    {{- include "notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: {{ .Values.backup.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "notes.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: backup
            {{- include "notes.dbClientLabel" . | nindent 12 }}
        spec:
          {{- include "notes.backupPodSpec" . | nindent 10 }}
{{- end }}
