apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes.fullname" . }}-postgres
  labels:
    {{- include "notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "notes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes.fullname" . }}-postgres-headless
  labels:
    {{- include "notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "notes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
